start = xml
xml = element xml {source, poem}
source = element source {title, author, date}
title = element title {level, text}
level = attribute level {text}
author = element author {text}
date = element date {when, text}
when = attribute when {xsd:int}
poem = element poem {title, lg+}
lg = element lg {ln+}
ln = element ln {n, (text | placeName | place | motif)*}
#old version below
#ln = element ln {n, mixed{placeName*, place*, motif?}}

placeName = element placeName {ref, text}
#old version below
#ref = attribute ref {text}
ref = attribute ref {"NYC-Harlem" | "NYC-Man" | "NYC-PennSt" | "PR" | "Cuba" | "Ha" | "Ja" | "Ga" | "Fla" | "La" 
| "NYC" | "NYC-Harlem" | "NYC-Brook" | "NYC-Bronx"}

place = element place {ref, text}
n = attribute n {xsd:int}
motif = element motif {text}